version: '3.7'

services:
  #Базовый образ для веб + php + ssh
  module1:
    build:
      context: apache-php
      args:
        SSH_PASS: ${USER_PASSWORD:-password}
        SSH_USER: ${USER_LOGIN:-login}
        #YII: ${YII:-false}
        VUE: ${VUE:-false}
        #REACT: ${REACT:-false}
        #ANGULAR: ${ANGULAR:-false}
    environment:
        - APACHE_RUN_USER=${USER_LOGIN:-login}
        - APACHE_RUN_GROUP=${USER_LOGIN:-login}
        - LC_CDPATH=/var/www/html
    restart: always
    container_name: ${USER_LOGIN:-login}_m1
    volumes:
      - ./data/${USER_LOGIN:-login}_m1:/var/www/html
      - ./apache-php/start.sh:/root/start.sh
      - ./apache-php/sshd_config:/etc/ssh/sshd_config
    ports:
       - ${SSH_PORT_M1:-1111}:22

  #Базовый образ для веб + php + ssh
  # module2:
  #   build:
  #     context: apache-php
  #     args:
  #       SSH_PASS: ${USER_PASSWORD:-password}
  #       SSH_USER: ${USER_LOGIN:-login}
  #       LARAVEL: ${LARAVEL:-false}
  #   environment:
  #       - APACHE_RUN_USER=${USER_LOGIN:-login}
  #       - APACHE_RUN_GROUP=${USER_LOGIN:-login}
  #       - LC_CDPATH=/var/www/html
  #   restart: always
  #   container_name: ${USER_LOGIN:-login}_m2
  #   volumes:
  #     - ./data/${USER_LOGIN:-login}_m2:/var/www/html
  #     - ./apache-php/start.sh:/root/start.sh
  #     - ./apache-php/sshd_config:/etc/ssh/sshd_config
  #   ports:
  #      - ${SSH_PORT_M2:-2222}:22

  #Образ для базы данных mariadb  
  mariadb:
      image: mariadb
      restart: always
      environment: 
          MYSQL_DATABASE: ${DB_NAME:-db}
          MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD:-password}
          MYSQL_USER: ${USER_LOGIN:-login}
          MYSQL_PASSWORD: ${USER_PASSWORD:-password}
      container_name: ${USER_LOGIN:-container}_mariadb
      volumes:
          - ./data/${USER_LOGIN:-container}_mariadb:/var/lib/mysql

  #Образ для phpmyadmin
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: ${USER_LOGIN:-container}_phpmyadmin
      environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=http://localhost:8080/phpmyadmin
      depends_on:
          - mariadb

  #Образ для проксирующего сервера
  proxy:
    build:
      context: ./proxy
      args:
        SERVER_NAME: ${SERVER_NAME:-localhost}
        WEB_PORT: ${WEB_PORT:-8080}
    container_name: ${USER_LOGIN:-container}_proxy
    restart: always
    ports:
      - ${WEB_PORT:-8080}:80
    depends_on:
      - module1
     # - module2
      - phpmyadmin